### ISSUE TITLE
Wordpress plug in

### ISSUE THREAD

**Issue by StephDing** [GreenInfo-Network/Calfornia-Farmland-Trust#1]
From the statement of work:
**Task:4** Plug In to Wordpress We will upload data to ArcGIS Online and style a public webmap using available Esri web tools (without custom code). Then we'll install the Esri Wordpress plugin (https://wordpress.org/plugins/embed-webmap/) and configure a Page in your Wordpress site to include the map, using the Plugin settings and no custom code. Please note that this estimate assumes that your Wordpress installation allows standard installation of plugins and that the Esri plugin will not conflict with other plugins you might be using. Managing plugin conflicts or custom theme issues is not included in this scope. Deliverables: Working embedded AGOL map on a Wordpress page 
**Estimated costs: $570 - $940, 4-6 hours**

The AGOL webmap ID: 7d1d2bfe2a264d7fb06478759e5ac97a
California Farmland Trust website: http://cafarmtrust.org/
Contact at CFT: Melanee Cottrill <mcottrill@cafarmtrust.org>

The AGOL map is under the GreenInfo account and the project name is California Farmland Trust

Please let me know if you need anything else!

**Comment by tomay** [comment]
@StephDing this is good to go. They actually want us to create the page? Or do they have a page already to add this to? 

There are quite a few options: 

Shortcode Options

    id – The webmap ID of the map you wish to embed. Get this from the URL bar on arcgis.com. See the “Screenshots” page for help. Example: [webmap id=”52475e6edb18471780858627b40460c2″]
    extent – in the “shortened” form. Use http://psstl.esri.com/apps/extenthelper/ for help. Example: [webmap extent=”-159.3635,7.093,-45.8967,63.7401″]
    height – specify the height, in pixels. Example: [webmap height=”600″]
    width – specify the width, in pixels. Example: [webmap width=”230″]
    zoom – Include zoom buttons. Example: [webmap id=”52475e6edb18471780858627b40460c2″ zoom]
    home – Include a home button. If this is included, the zoom buttons will automatically be included. Example: [webmap id=”52475e6edb18471780858627b40460c2″ home]
    scale – Include a scale bar. Example: [webmap scale id=”52475e6edb18471780858627b40460c2″]
    legend – Include a legend button. Example: [webmap id=”52475e6edb18471780858627b40460c2″ legend]
    search – Include a location search textbox. Example: [webmap id=”52475e6edb18471780858627b40460c2″ search]
    searchextent – When using ‘search’ (above), only search the current extent. Example: [webmap id=”52475e6edb18471780858627b40460c2″ search searchextent]
    basemap_toggle – Show a basemap toggle. Must also include ‘alt_basemap’ to indicate alternate basemap that will show when the toggle button is clicked. Example: [webmap id=”52475e6edb18471780858627b40460c2″ basemap_toggle alt_basemap=”streets”]
    basemap_gallery – Include a basemap menu. [webmap id=”52475e6edb18471780858627b40460c2″ basemap_gallery]
    view-larger-link – Include a link below the map to view the map in a larger window. Example: [webmap id=”52475e6edb18471780858627b40460c2″ view-larger-link]
    disable_scroll – When the mouse is over the map, the scroll will not zoom the map if this is added. Example: [webmap id=”52475e6edb18471780858627b40460c2″ disable_scroll]
    details – Show the map details pane. Example: [webmap id=”52475e6edb18471780858627b40460c2″ details]

One of the most important ones is probably `extent`. Do you have a bounding box in mind? If so, can you send it to me? Looks like it's two corners (lower left and top right) in geographic coords. 

The others, we can set up, or they can play with. It's just a matter of adding options to the short code and viewing a draft.

**Comment by tomay** [comment]
Here's an example of a working short code:
```
[webmap id="7d1d2bfe2a264d7fb06478759e5ac97a" height="600"]
```

**Comment by StephDing** [comment]
I'll send an email to Melanee and cc you asking which page they want the AGOL map on. As for extent and size, that's pretty much up to our discretion, I think we just want to show California. 
I'm afraid your example of the working short code doesn't mean much to me.

**Comment by StephDing** [comment]
I was just about to respond to Melanee's last email and re read it. She said she created a map page for the map already. Do you mind replying to her email with your questions? I don't mind emailing, but I'm not to familiar with the wordpress setup.

**Comment by tomay** [comment]
only hitch we noticed is that the shortcode can contain hidden html characters (perhaps if copied and pasted from email?). In any case, these are revealed when editing the content using the "Text" tab, not "Visual"
